### ISSUE TITLE
[REJECTED] Windows standalone binary

### ISSUE THREAD

**Issue by sergeevabc** [iCHAIT/moviemon#12]
Dear Chaitanya,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows only?
I’m told that [py2exe][1] might help you to achieve that.

[1]: http://py2exe.org/

**Comment by iCHAIT** [comment]
Hi @sergeevabc 

I really appreciate that you found `moviemon` useful.

But out of curiosity, why do you want an executable for this at all? I mean its a command line python tool with pretty minimal platform dependency (and which can be easily fixed by amending the code), and for using it you can simply install it [with pip](https://github.com/iCHAIT/moviemon#using-pip) or [build it from source](https://github.com/iCHAIT/moviemon#get-the-latest-build-from-the-source).

To be honest, I don't really understand the point of creating an executable for a command line tool.

Please let me know what you think :)

**Comment by sergeevabc** [comment]
Current state of Moviemon requires Python to be installed on host machine which is a dependency itself.
Other CLI gems like [sysinternals][1], [ffmpeg][2], [jdupes][3], [wget][4], [pandoc][5], [sift][6] could be run simply from USB stick.

[1]: https://live.sysinternals.com/
[2]: http://www.videohelp.com/software/ffmpeg
[3]: https://github.com/jbruchon/jdupes/
[4]: https://eternallybored.org/misc/wget/
[5]: https://github.com/jgm/pandoc
[6]: https://github.com/svent/sift/

**Comment by iCHAIT** [comment]
Hmm, I get ur point now.

But to be honest with you, I don't have much time to work on this right now, so you shouldn't expect an executable for this coming out any soon, though I would really appreciate a PR by you or someone else who is interested on working on it :smiley:

**Comment by sergeevabc** [comment]
Thank you for letting me know, Chaitanya.

**Comment by iCHAIT** [comment]
I'll actually keep this open in case someone is interested in working on this, and so that its present under my list of to do 's for when I have time :)

**Comment by sergeevabc** [comment]
Six months passed. It seems nobody is interested.
